config/routes.rb
Rails.application.routes.draw do
  devise_for :reps
  resources :clients
  resources :pages, only: [:index]
  resources :products, only: [:index, :show]

  resources :sales do
  	resources :clients
  	resources :items
  	resources :products
  end
   
  root 'pages#index'
end

app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :rep

	validates :name, presence: true, length: {minimum: 2}  	
  	validates :address, presence: true, length: { minimum: 5}
  	validates :phone, presence: true, numericality: { only_integer: true }
  	validates :email, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/rep.rb
class Rep < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :clients
  has_many :sales
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :client
  belongs_to :rep
  has_many :items

  accepts_nested_attributes_for :items, :allow_destroy => true

  def update_price(items)
    items.each do |item|
      @product =Product.find(item.product_id)
      item.price = @product.price
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :find_client, only: [:show, :edit, :update, :destroy]
	
	def index
		@clients = Client.where(rep_id: current_rep.id)
	end

	def show
	end

	def create
		@client = Client.new(client_params)
		@client.rep_id = current_rep.id

		if @client.save
			redirect_to @client
		else
			render 'new'
		end
	end

	def new
		@client = Client.new
	end

	def edit
	end

	def update
		if @client.update(client_params)
			redirect_to @client
		else
			render 'edit'
		end
	end

	def destroy
		@client.destroy
		redirect_to root_path
	end

	private

	def client_params
		params.require(:client).permit(:name, :address, :phone, :email, :rep_id)
	end

	def find_client
		@client = Client.find(params[:id])
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show]
	
	def create
		@item = Item.new(item_params)
		
		if @item.save
			redirect_to sales_path
		else
			render 'new'
		end
	end

	def new
		@item = Item.new
	end

	private

	def item_params
		params.require(:item).permit(:product, :quantity)
	end

	def find_item
		@item = Item.find(params[:id])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		if current_rep
			@rep = current_rep.email
		else
			@rep = ""
		end
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :find_product, only: [:show]

	def index
	@products = Product.all.order("name ASC"); 

	respond_to do |format|
			format.html
			format.json {render json: @products}
		end


	end

	def show

		respond_to do |format|
			format.html
			format.json {render json: @product}
		end

	end

	private

	def find_product
		@product = Product.find(params[:id])
	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	before_action :find_sale, only: [:show, :destroy]

	def index
		@sales = Sale.where(rep_id: current_rep.id)
	end

	def show
		sale = find_sale
		@items = Item.where(sale_id: (find_sale).id)
		
		sale.update_price(@items)
		
		@client = Client.find(sale.client_id)

		@date = sale.created_at.strftime("%d %b. %Y")
		@total =0;
		
		@items.each do |item|
			@total += item.price * item.quantity
		end
	end
	
	def create
		@sale = Sale.new(sale_params)
		@sale.rep_id = current_rep.id
			
		if @sale.save			
			redirect_to @sale	
		else
			render 'new'
		end	
	end

	def destroy
		Item.destroy_all(sale_id: @sale.id)
		@sale.destroy
		redirect_to root_path, notice: "Successfully deleted "
	end

	def new
		@sale = Sale.new
		@sale.items.build
	end

	private

	def sale_params
		params.require(:sale).permit(:client_id, items_attributes: [:id, :product_id, :quantity, :_destroy])
	end

	def find_sale
		@sale = Sale.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_screens_helper.rb
module MainScreensHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/clients/_form.html.haml
= simple_form_for @client do |f|
	=f.input :name
	=f.input :address
	=f.input :phone
	=f.input :email
	=f.submit 'Save'

app/views/clients/edit.html.haml
%h2 Edit Client
= render 'form'

=link_to "Cancel", client_path

app/views/clients/index.html.haml
%h2 Clients
%h4=link_to "New Client", new_client_path
%hr
- @clients.each do |client|
	%h5= client.name
	%p= client.phone
	%p= link_to "details", client
	%hr

app/views/clients/new.html.haml
%h2 New Client

= render 'form'

app/views/clients/show.html.haml
%h4 Name: #{@client.name}
%h4 Address: #{@client.address}
%h4 Phone: #{@client.phone} 
%h4 Email: #{@client.email}
%br
= link_to "Edit", edit_client_path(@client)
=link_to "Delete", client_path(@client), method: :delete, data: {confirm: "Are you sure?"}
= link_to "Back", clients_path

app/views/items/_form.html.haml
= simple_form_for item do |f|
	
	=f.association :product, as: :check_boxes
	=f.input :quantity
	
	=f.submit

app/views/items/new.html.haml
%h1 new item

= render 'form'

app/views/layouts/application.html.haml
!!!!
%html
%head
	%title Rails Project - Thiago Orniz
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	= csrf_meta_tags
%body
	- if notice
		#msg
			%p.notice= notice
	-elsif alert
		#msg
			%p.alert= alert
			
	%ul.nav.nav-tabs
		- if rep_signed_in?
			%li= link_to "Home", pages_path
			%li= link_to "Clients", clients_path
			%li= link_to "Products", products_path
			%li= link_to "Sales", sales_path
			%li= link_to "Sign out", destroy_rep_session_path, method: :delete
		- else
			%li= link_to "Sign in", new_rep_session_path

.container
	=yield

app/views/pages/index.html.haml
.wrapperCentered

	%h3 Hello, #{@rep}
	%br

	- if(!current_rep)
		%p Be part of our team
		= link_to "Sign up", new_rep_registration_path

	%br
	%br
	%br

	#slideshow
		=image_tag "slide1.jpg", height: '350', width: '350', :class => "active"
		=image_tag "slide2.jpg", height: '350', width: '350'
		=image_tag "slide3.jpg", height: '350', width: '350'
	

	

app/views/pages/show.html.haml
%h2 link_to "Clients" clients

app/views/products/index.html.haml

%h2 Products
%br
%hr
- @products.each do |product|
	%h5= product.name
	%p$ #{product.price}
	%p= link_to "details", product
	%hr	



app/views/products/show.html.haml
%h4 Product: #{@product.name}
%h4 Price: #{@product.price}
%h4 Comment: #{@product.comment}
=image_tag(@product.url, :alt => @product.name, :width => 300, :height => 300)
%br
%br
= link_to "Back", clients_path

app/views/sales/_form.html.haml
= simple_form_for @sale, html: { id: 'sale-form' }  do |f|
	= f.association :client, :as => :collection_select, collection: Client.where('rep_id = ?',current_rep.id), default: :first

	.items
		= f.simple_fields_for :items do |i|
			= render 'item_fields', f: i

	=link_to_add_association 'Add Item', f , :items, {'data-association-insertion-node' => '#sale-form .items', 'data-association-insertion-method' => 'append'}
	
	=f.submit 'Save'

app/views/sales/_item_fields.html.haml

.nested-fields
    =f.association :product, default: :first
    =f.input :quantity,collection: 1..99, default: 1
    =link_to_remove_association "Remove", f

app/views/sales/index.html.haml
%h2 Sales
%h4=link_to "New Sale", new_sale_path
%hr
- @sales.each do |sale|
	%h5= Client.find(sale.client_id).name
	%h5=link_to sale.created_at.strftime("%d %b. %Y"), sale
	%hr

app/views/sales/new.html.haml
%h2 New Sale

= render 'form'

app/views/sales/show.html.haml

%h3 Client: #{@client.name}
%p Date: #{@date}
%table
	%tbody
		%tr
			%th Product 
			%th Price 
			%th Quantity 

		- @items.each do |item|
			%tr
				%td=item.product.name
				%td=item.price
				%td=item.quantity

%h3 Total: $#{@total}

= link_to "Delete", sale_path, method: :delete, data: {confirm: "Are you sure?" }
